#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Mountain House Sports and Recreation Club
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Organization to promote Sports and Recreation in city of Mountain House
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Mountain House Sports and Recreation Club (MHSRC) is a nonprofit organization dedicated to enhancing community life in Mountain House through sports, recreation, and engaging activities. Our mission is to promote an active, healthy, and connected community by offering diverse programs and events that bring people together.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: support@mhsrc.org
org_street_address:  #Please include suite number on the line below
org_address_suite: 
org_city: Mountain House
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  95391
org_phone: 

#SOCIAL MEDIA
org_twitter_username: mhsrc
org_facebook_username: mhsrc
org_instagram_username: mhsrc

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: 
tinyletter_username: 

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: default

custom:
  short_nm: MHSRC
  header: header.png
  mission_statement: >
    To unite and empower the residents of Mountain House by fostering a vibrant, inclusive community through sports, cultural celebrations, and service initiatives. We are committed to creating opportunities for connection, personal growth, and community pride, ensuring that every individual feels valued and inspired to contribute to the collective well-being of our town.
  activities: >
    We organize a variety of sports tournaments and leagues that cater to all ages and skill levels. Whether it's volleyball, or throw ball, our events are designed to foster teamwork and friendly competition.
    Community Events: From cultural festivals and holiday celebrations to family-friendly activities, we host events that celebrate the spirit of Mountain House. Our goal is to create memorable experiences and strengthen community bonds.
    Recreational Activities: Our recreational programs include fitness classes, art workshops, and more. We offer opportunities for personal growth and leisure, helping everyone in our community stay active and engaged.

events:
  - name: Volleyball & Throwball Tournament
    description: >
      Mountain House Sports and Recreation Club Organizing Volleyball & Throwball Tournament on October 20th At Central Community Park, 25th Main Street, Mountain House, CA 95391.<br>
      <br>We are a non-profit charity organization under section 501 (c)(3) - EIN 93-2235954  - so donors can claim tax benefit. <br>
      <br>
      <b>Registration Fees:</b><br>
      Volley Ball : $160<br>
      Throw Ball: $120<br>
      <br>
      <b>Payment Methods:</b><br>
      Zelle or PayPal : mhsrc.org@gmail.com<br>
      Check payable to "MHSRC"<br>
      <br><b>Contacts: </b><br>
        - Rupesh (309-749-8074)<br>
        - Krishnan (404-200-6892)<br>
    date: 10/20/2024 8 AM
    registration_deadline: Sunday October 6th 2024
    Contacts: 
      - Rupesh (309-749-8074)
      - Krishnan (404-200-6892)
    registration_url: https://tinyurl.com/mhsrc2024
    poster: header.png

leadership:
  - role: Founder & Chairman
    name: Suresh Vuyyuru
    photo: suresh.jpeg
    intro: >
      Suresh Vuyyuru, the visionary behind MHSRC, founded the club in 2020 with a mission to build a strong, inclusive community through sports and cultural activities. He leads the organization with a focus on strategic growth, ensuring that MHSRC continues to serve the Mountain House community effectively.
  - role: President
    name: Srinivas Veeramallu
    intro: >
      Srinivas Veeramallu plays a critical role in the day-to-day operations of MHSRC, driving the club's initiatives and ensuring that all programs align with its mission. As President, he is responsible for guiding the team in executing successful events and programs.
  - role: Vice President
    name: Shravan Yempati
    intro: >
      Shravan Yempati supports the President in overseeing the club's activities and initiatives. He plays a key role in community outreach and ensuring the smooth execution of MHSRC's events.
  - role: Secretary
    name: Yogesh Reddy
    intro: >
      Yogesh is responsible for maintaining clear communication within the leadership team and with the community. He ensures that all administrative tasks are handled efficiently and that important information is documented and shared.
  - role: Treasurer
    name: Krishnan Nadadhur
    photo: krishnan.jpeg
    intro: >
      Krishnan manages the financial health of MHSRC, overseeing all transactions, budgeting, and reporting. He ensures transparency in financial matters and supports the funding of events and programs.
  - role: Joint Secretary
    name: Brij Kishore Rai
    photo: brij.jpg
    intro: >
      Brij Kishore Rai assists in the administrative functions of the club, working closely with the Secretary to manage correspondence, documentation, and communication.
  - role: Communications Chair
    name: Kaleem Mohammed
    photo: kaleem.jpeg
    intro: >
      Kaleem is responsible for promoting MHSRC's mission, events, and programs to the wider community. He manages the club's social media platforms, website content, and other communication channels.
  - role: Community Service Chair
    name: Sreekanth Godey
    intro: >
      Sreekanth Godey leads MHSRC's community service initiatives, organizing events and programs that benefit the Mountain House community and encourage active participation.
  - role: Culturalal Activities Chair
    name: Pradeep Pisharram
    photo: pradeep.jpg
    intro: >
      Pradeep is in charge of organizing cultural events that celebrate the diversity of the Mountain House community. He ensures that these events reflect the values and traditions of the residents.
  - role: Youth Services Chair
    name: Sahithi Godey
    intro: >
      Sahithi Godey focuses on engaging the youth in the community through sports and cultural activities. She develops programs that are inclusive and cater to the interests of younger residents.
  - role: Joint Treasurer
    name: Murali Bonthu
    intro: >
      Murali Bonthu works alongside the Treasurer to manage MHSRC's financial matters, ensuring that all financial records are accurate and that funds are allocated appropriately.
  - role: Executive Member
    name: Dev Sutar
    intro: >
      Dev Sutar contributes to the strategic planning and execution of MHSRC's events, offering his expertise and support to ensure the success of the club's initiatives.
  - role: Executive Member
    name: Venu Thottempudi
    intro: >
      Venu's commitment to fostering a strong, inclusive community makes him an invaluable member of the executive committee.
  - role: Executive Member
    name: Santosh Mahajan
    intro: >
      Santosh Mahajan supports the leadership team with his experience and commitment, helping to drive the club's mission and ensure the successful execution of its events.

event_photos:
  - AMR_3620.jpg
  - AMR_3625.jpg
  - AMR_3236.jpg
  - AMR_3277.jpg
  - AMR_3311.jpg
  - AMR_3361.jpg
  - AMR_3419.jpg
  - AMR_3425.jpg
  - AMR_3469.jpg
  - AMR_3601.jpg
  - AMR_3603.jpg
more_photos:
  - AMR_3620.jpg
  - AMR_3625.jpg
  - AMR_3236.jpg
  - AMR_3277.jpg
  - AMR_3311.jpg
  - AMR_3361.jpg
  - AMR_3419.jpg
  - AMR_3425.jpg
  - AMR_3469.jpg
  - AMR_3601.jpg
  - AMR_3603.jpg        
# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
